[project]
name = "surgeon"
description = "A C/C++ source generation library."
version = "0.1.0"
requires-python = ">=3.11.0"
authors = [{ name = "Omer Lubin", email = "omer.lubin.1337@gmail.com" }]
dependencies = ["case-converter"]

[project.optional-dependencies]
dev = ["pre-commit", "black", "ruff", "mypy", "pytest"]

[tool.mypy]
strict = true
pretty = true
exclude = ["build"]

[tool.ruff]
select = ["ALL"]
ignore = ["D", "EM", "ANN101", "ANN102", "TRY003"]

[tool.ruff.per-file-ignores]
"test_*.py" = ["S101"]
