name: Test Python Package

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with: { python-version: "3.11" }

      - name: Upgrade pip
        run: python -m pip install --upgrade pip  

      - name: Install dependencies
        run: pip install .[dev]

      - name: Test with pre-commit
        run: pre-commit run --all-files

      - name: Test with pytest
        run: pytest
