name: Publish Python Package

on:
  push:
    tags: [v*]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with: { python-version: "3.11" }

      - name: Upgrade pip
        run: python -m pip install --upgrade pip  

      - name: Install dependencies
        run: pip install .[dev]

      - name: Test with pre-commit
        run: pre-commit run --all-files

      - name: Test with pytest
        run: pytest


  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with: { python-version: "3.11" }

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install build
        run: pip install build

      - name: Build package
        run: python -m build

      - name: Upload package artifacts
        uses: actions/upload-artifact@v3
        with:
          name: package-artifacts
          path: dist/

  release:
    runs-on: ubunute-latest
    needs: build
    steps:
      - name: Download package artifacts
        uses: actions/download-artifact@v3
        with:
          name: package-artifacts

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{  github.ref_name }}
          artifacts: dist/
          bodyFile: readme.md

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions: { id-token: write }
    steps:
      - name: Download package artifacts
        uses: actions/download-artifact@v3
        with:
          name: package-artifacts

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
